name = "cluster_config"

# addresses that the nodes will listen on 
addresses = [
	"localhost:4000",
	"localhost:4001",
	"localhost:4002",
	"localhost:4004",
	"localhost:4005",
]

# used by dev-tools to hijack a cluster with higher terms
# faster or slower heartbeats
forceTerm = 101
heartbeat = 10

# TODO: tells simulation to continue until it's in control of the raft
persist = false
