peers = ["localhost:5000", "localhost:5001", "localhost:5002", "localhost:5003"]
pprof_addr = "localhost:6061"

[cluster_settings]
  heartbeat = 800
  min_interval = 1500
  max_interval = 1800
  [cluster_settings.topology]
    type = "cluster"
    ports = [5000, 5001, 5002, 5003]
