peers = [
"localhost:5000", 
"localhost:5001", 
"localhost:5002", 
"localhost:5003",
"localhost:5004",
"localhost:5005",
"localhost:5006",
"localhost:5007",
"localhost:5008",
"localhost:5009",
"localhost:5010",
"localhost:5011",
"localhost:5012",
]
pprof_addr = "localhost:6061"

[cluster_settings]
  heartbeat = 100
  min_interval = 1300
  max_interval = 2100
  [cluster_settings.topology]
    type = "cluster"
