peers = [
"0.0.0.0:5001", 
"0.0.0.0:5002", 
]
pprof_addr = "0.0.0.0:6061"

[cluster_settings]
  heartbeat = 800
  min_interval = 1200
  max_interval = 1900
  [cluster_settings.topology]
    type = "cluster"
