name = "cluster_config"

# number of nodes to spin in a cluster. 
totalNodes = 1

# addresses that the nodes will listen on 
addresses = [
	"localhost:4000",
	"localhost:4001",
	"localhost:4002",
]

# used by dev-tools to hijack a cluster with higher terms
# faster or slower heartbeats
forceTerm = 101
heartbeat = 10

# tells dev-tools to continue until it's in control of the raft
persist = false
