name = "deploy.toml"

[[machines]]
ip = "ip1"
host = "0.0.0.0"
listen_port = 4001
pprof_port = 6061
ssh_path = "/Users/eghosa.aiwuyo/.ssh/persona_mp3"
login_user = "root"
opts = []

[[machines]]
ip = "ip2"
host = "0.0.0.0"
listen_port = 4001
pprof_port = 6061
ssh_path = "/home/.ssh/ip2"
login_user = "root"
opts = []

[[machines]]
ip = "ip3"
host = "0.0.0.0"
listen_port = 4001
pprof_port = 6061
ssh_path = "/home/.ssh/ip3"
login_user = "root"
opts = []


[cluster_settings]
heartbeat = 200
min_interval = 400
max_interval = 1500
mode = "single"


# Each machine/node will have peers that are the other nodes. This will by dynamically derived by dock
# pprof_port is what will be exposed for the go pproff for monitoring
# listen_port is what port the node will bind to and listen on
# opts means that the node will have special settings
# To also keep with the previous cluster configuration, the mode simply tells
# the program how to run this node. 
# "single" only run this node 
# "cluster" run this node, and it's peers on this machine as a single process
# "isolated" run this node and it's peers on this machine as seperate processes


# dock will generate a cluster_config.toml for each of these nodes and then deploy them on their ips
# Each cluster_config.toml would look like this:
# host = 0.0.0.0 or localhost
# listen_port = 4001
# pprof_port = 6061
# peers = ["some-ip-address-2:4002", "some-ip-address-3:4003"]

# ssh_path = "/absolute/path"
# heartbeat = 200
# min_interval = 400
# max_interval = 1500
