name = "deploy.toml"
# if true, dock will ssh into these machines and run the binaries
deploy = false

[[machines]]
ip = "ip1"
host = "0.0.0.0"
listen_port = 4000
# exposed to go's http pprof
pprof_port = 6061
ssh_path = "/home/.ssh/ip1"
login_user = "root"
opts = []

[[machines]]
ip = "ip2"
host = "0.0.0.0"
listen_port = 5000
pprof_port = 6061
ssh_path = "/home/.ssh/ip2"
login_user = "root"
opts = []

[[machines]]
ip = "ip3"
host = "0.0.0.0"
listen_port = 1738
pprof_port = 6061
ssh_path = "/home/.ssh/ip3"
login_user = "root"
opts = []


[cluster_settings]
heartbeat = 800
min_interval = 1100
max_interval = 1500

[cluster_settings.topology]
type = "node"
ports = [5000, 5001, 5002, 5003]


# Each machine/node will have peers that are the other nodes. This will by dynamically derived by dock
# pprof_port is what will be exposed for the go pproff for monitoring
# listen_port is what port the node will bind to and listen on
# opts means that the node will have special settings
# To also keep with the previous cluster configuration, the mode simply tells
# the program how to run this node. 

# TOPOLOGY: This decides how these nodes will run on a machine. "node", "cluster", "isolated"

# "node" only run this node on this machine
# -------------
###########################################
# Node Mode configuration file  
###########################################
# id = 1
# info = "id: 1, ip: ip1, generatedAt: 2026-07-18, by: dock"
# listen = "0.0.0.0:4000"
# pprof_addr = "0.0.0.0:6061"
# peers = ["ip2:5000", "ip3:1738"]

# [cluster_settings]
#   heartbeat = 800
#   min_interval = 1100
#   max_interval = 1500
#   [cluster_settings.topology]
#     type = "node"
#     ports = [5000, 5001, 5002, 5003]


# "cluster" mode will generate a node config file,
# -------------
#  instead of individual config files for the cluster to run
#  the host addresses are by default changed to 'localhost', so are 
#  all the peers. You have to specify what ports the peers will run on. The number of 
#  nodes created will be the number of nodes that will be running at any given time on 
#  this device. In that case no machines can be specified, just the cluster settings and the ports
###########################################
# Cluster Mode configuration file  
###########################################
# peers = ["localhost:5000", "localhost:5001", "localhost:5002", "localhost:5003"]
# pprof_addr = "localhost:6061"
#
# [cluster_settings]
#   heartbeat = 800
#   min_interval = 1100
#   max_interval = 1500
#   [cluster_settings.topology]
#     type = "cluster"
#     ports = [5000, 5001, 5002, 5003]
#

# "isolated" run this node and it's peers on this machine as seperate processes
# -------------
# Not yet implemented

